#!/bin/bash
cd /tmp/rom # Depends on where source got synced
rm -rf .repo # lets remove unnecessary things, so that no storage issue can occur

rm -rf external/json-c && git clone https://github.com/LineageOS/android_external_json-c.git external/json-c
git clone https://github.com/LineageOS/android_hardware_qcom_media.git
git clone https://github.com/erwinabs/hardware_qcom_audio
rm -r hardware/qcom-caf/msm8996/audio/mm-audio/aenc-aac/qdsp6/inc/
mv android_hardware_qcom_media/msm8996/mm-core/inc/ hardware/qcom-caf/msm8996/audio/mm-audio/aenc-aac/qdsp6/inc/
mv mm-audio/aenc-aac/qdsp6/inc/ hardware/qcom-caf/msm8996/audio/mm-audio/aenc-aac/qdsp6/inc/
echo "Moved"

# Normal build steps
source build/envsetup.sh 
lunch kangos_X01AD-userdebug ##edit this

export SKIP_API_CHECKS=true
export SKIP_ABI_CHECKS=true
export ALLOW_MISSING_DEPENDENCIES=true
cd /tmp/rom
export CCACHE_DIR=/tmp/ccache ##set additional flags if you need(optional)
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1

ccache -M 30G
ccache -o compression=true
ccache -z
ccache -c

up(){
	curl --upload-file $1 https://transfer.sh/
}

make_metalava(){
	mka api-stubs-docs
	mka system-api-stubs-docs
	mka test-api-stubs-docs
}

make_rom(){
	make bacon -j30 
	zip=$(up out/target/product/X01AD/*zip) ##edit this
	echo " "
	echo "$zip"
	curl -sL https://git.io/file-transfer | sh
	./transfer wet out/target/product/X01AD/*zip
}

make_metalava
make_rom &
sleep 4400 && kill "$!"
ls hardware/qcom-caf/msm8996/audio/mm-audio/aenc-aac/qdsp6/inc/
