#!/bin/bash
cd /tmp/rom # Depends on where source got synced
rm -rf .repo # lets remove unnecessary things, so that no storage issue can occur

# Normal build steps
source build/envsetup.sh 
lunch kangos_X01AD-userdebug  ##edit this
export SKIP_API_CHECKS=true
export SKIP_ABI_CHECKS=true
export ALLOW_MISSING_DEPENDENCIES=true
cd /tmp/rom
export CCACHE_DIR=/tmp/ccache ##set additional flags if you need(optional)
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1

ccache -M 30G
ccache -o compression=true
ccache -z
ccache -c

up(){
	curl --upload-file $1 https://transfer.sh/
}

make_metalava(){
	mka api-stubs-docs
	mka system-api-stubs-docs
	mka test-api-stubs-docs
}

make_rom(){
	make bacon -j30
	zip=$(up out/target/product/X01AD/*zip) ##edit this
	echo " "
	echo "$zip"
	curl -sL https://git.io/file-transfer | sh
	./transfer wet out/target/product/X01AD/*zip
}

make_metalava
make_rom
