#!/bin/bash

url=https://roms.spxd007.workers.dev/kanghub.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf kanghub.tar.gz
echo "unzip done"
find kanghub.tar.gz -delete
